export const names_icons_skills = [
  "devicon-html5-plain-wordmark colored",
  "devicon-css3-plain-wordmark colored",
  "devicon-javascript-plain colored",
  "devicon-typescript-plain colored",
  "devicon-nextjs-original-wordmark colored",
  "devicon-react-original-wordmark colored",
  "devicon-redux-original colored",
  "devicon-bootstrap-plain-wordmark colored",
  "devicon-materialui-plain colored",
  "devicon-tailwindcss-original-wordmark colored",
  "devicon-docker-plain-wordmark colored",
  "devicon-laravel-plain-wordmark colored",
  "devicon-cakephp-plain-wordmark colored",
  "devicon-nestjs-plain-wordmark colored",
  "devicon-nodejs-plain-wordmark colored",
  "devicon-git-plain-wordmark colored",
  "devicon-github-original-wordmark colored",
  "devicon-gitlab-plain-wordmark colored",
  "devicon-ubuntu-plain-wordmark colored",
  "devicon-mysql-plain-wordmark colored",
  "devicon-postgresql-plain-wordmark colored",
  "devicon-npm-original-wordmark colored",
];
